### ISSUE TITLE
how to use this in laravel ?

### ISSUE THREAD

**Issue by moeinrahimi** [nackjicholson/monolog-gitter-im#3]
hi
the title says the words, i'm a beginner and i just want to use this class in laravel logging

**Comment by nackjicholson** [comment]
Hi,

I have never used laravel so I don't know how to help you. If laravel uses monolog as it's logger, then you should be able to add this handler to laravels logger instance.

I have not used or modified this code in almost two years, thanks for the interest I hope it's useful to you, but I'm not actively maintaining this code.

Cheers,

-Will
